# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='square_messages.proto',
  package='messages',
  serialized_pb='\n\x15square_messages.proto\x12\x08messages\"\x1d\n\x0csquare_input\x12\r\n\x05value\x18\x01 \x02(\x03\"\x1e\n\rsquare_output\x12\r\n\x05value\x18\x01 \x02(\x03')




_SQUARE_INPUT = descriptor.Descriptor(
  name='square_input',
  full_name='messages.square_input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.square_input.value', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=64,
)


_SQUARE_OUTPUT = descriptor.Descriptor(
  name='square_output',
  full_name='messages.square_output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.square_output.value', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=96,
)



class square_input(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SQUARE_INPUT
  
  # @@protoc_insertion_point(class_scope:messages.square_input)

class square_output(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SQUARE_OUTPUT
  
  # @@protoc_insertion_point(class_scope:messages.square_output)

# @@protoc_insertion_point(module_scope)
